config/routes.rb
Rails.application.routes.draw do

  resources :pdf_forms

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pdf_forms_controller.rb
# require '/lib/pdfs/test.pdf.form.rb'
class PdfFormsController < ApplicationController
  # before_action :set_pdf_form, only: [:show, :edit, :update, :destroy]
  
  # GET /pdf_forms
  # GET /pdf_forms.json
  def index
    
    # render :pdf => TestPdfForm.new.export,type: 'application/pdf'
    respond_to do |format|
      format.pdf {send_file TestPdfForm.new.export,type: 'application/pdf', disposition: 'inline'}  
    end
    # a = TestPdfForm.new
    # render json: {field_names:a}
  end

  # GET /pdf_forms/1
  # GET /pdf_forms/1.json
  def show
  end

  # GET /pdf_forms/new
  def new
    @pdf_form = PdfForm.new
  end

  # GET /pdf_forms/1/edit
  def edit
  end

  # POST /pdf_forms
  # POST /pdf_forms.json
  def create
    @pdf_form = PdfForm.new(pdf_form_params)

    respond_to do |format|
      if @pdf_form.save
        format.html { redirect_to @pdf_form, notice: 'Pdf form was successfully created.' }
        format.json { render :show, status: :created, location: @pdf_form }
      else
        format.html { render :new }
        format.json { render json: @pdf_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pdf_forms/1
  # PATCH/PUT /pdf_forms/1.json
  def update
    respond_to do |format|
      if @pdf_form.update(pdf_form_params)
        format.html { redirect_to @pdf_form, notice: 'Pdf form was successfully updated.' }
        format.json { render :show, status: :ok, location: @pdf_form }
      else
        format.html { render :edit }
        format.json { render json: @pdf_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdf_forms/1
  # DELETE /pdf_forms/1.json
  def destroy
    @pdf_form.destroy
    respond_to do |format|
      format.html { redirect_to pdf_forms_url, notice: 'Pdf form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdf_form
      @pdf_form = PdfForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pdf_form_params
      params[:pdf_form]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdf_forms_helper.rb
module PdfFormsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDFForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pdf_forms/_form.html.erb
<%= form_for(@pdf_form) do |f| %>
  <% if @pdf_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pdf_form.errors.count, "error") %> prohibited this pdf_form from being saved:</h2>

      <ul>
      <% @pdf_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pdf_forms/edit.html.erb
<h1>Editing Pdf Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @pdf_form %> |
<%= link_to 'Back', pdf_forms_path %>

app/views/pdf_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pdf Forms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pdf_forms.each do |pdf_form| %>
      <tr>
        <td><%= link_to 'Show', pdf_form %></td>
        <td><%= link_to 'Edit', edit_pdf_form_path(pdf_form) %></td>
        <td><%= link_to 'Destroy', pdf_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pdf form', new_pdf_form_path %>

app/views/pdf_forms/new.html.erb
<h1>New Pdf Form</h1>

<%= render 'form' %>

<%= link_to 'Back', pdf_forms_path %>

app/views/pdf_forms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pdf_form_path(@pdf_form) %> |
<%= link_to 'Back', pdf_forms_path %>